services:
  - type: web
    name: sam-brend-backend
    env: docker
    dockerContext: .
    plan: free # Change if needed
    envVars:
      - key: PORT
        value: 10000
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "*" # To be updated with Render domain
      - key: DATABASE_URL
        fromDatabase:
          name: sam-brend-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: sam-brend-redis
          property: connectionString
      - key: DJANGO_SUPERUSER_PHONE
        value: "998901234567"
      - key: DJANGO_SUPERUSER_PASSWORD
        generateValue: true
      - key: DJANGO_SUPERUSER_FIRST_NAME
        value: Admin
      - key: DJANGO_SUPERUSER_LAST_NAME
        value: User
      - key: EMAIL_ADDRESS
        value: EMAIL_ADDRESS
  - type: redis
    name: sam-brend-redis
    plan: free
    ipAllowList: []

databases:
  - name: sam-brend-db
    plan: free
