# Generated by Django 6.0.3 on 2026-03-09 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_company_alter_sale_tariff_alter_sale_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariff',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tariffs', to='apps.company'),
        ),
    ]
