# Generated by Django 6.0.3 on 2026-03-10 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_user_plain_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreport',
            name='location_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='location_lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
