# Generated by Django 6.0.3 on 2026-03-19 20:39

import api_v1.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0007_dailyreport_location_lat_dailyreport_location_lng'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='date',
            field=models.DateField(default=api_v1.utils.get_uz_now),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='date',
            field=models.DateField(default=api_v1.utils.get_uz_now),
        ),
        migrations.AlterField(
            model_name='sale',
            name='date',
            field=models.DateField(default=api_v1.utils.get_uz_now),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
