# Generated by Django 6.0.3 on 2026-03-20 11:38

import apps.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0009_operatorrating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='checkins/', validators=[apps.models.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='saleslink',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='sales_links/', validators=[apps.models.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', validators=[apps.models.validate_image_size]),
        ),
    ]
