# Generated by Django 6.0.3 on 2026-03-20 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0011_alter_checkin_date_alter_dailyreport_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sale',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterField(
            model_name='user',
            name='is_approved',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('operator', 'Operator'), ('manager', 'Manager'), ('navbatchi_operator', 'Duty Operator')], db_index=True, default='operator', max_length=20),
        ),
        migrations.AddIndex(
            model_name='operatorrating',
            index=models.Index(fields=['operator', 'date'], name='apps_operat_operato_b7bf4e_idx'),
        ),
        migrations.AddIndex(
            model_name='operatorrating',
            index=models.Index(fields=['rated_by', 'date'], name='apps_operat_rated_b_6c7e2f_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['user', 'date'], name='apps_sale_user_id_0932e3_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['company', 'date'], name='apps_sale_company_793a33_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['tariff', 'date'], name='apps_sale_tariff__15a3af_idx'),
        ),
    ]
