# Generated by Django 6.0.3 on 2026-03-21 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0013_globalsetting'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tariff',
            unique_together={('company', 'name')},
        ),
        migrations.AddField(
            model_name='message',
            name='text_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='text_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='text_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='rule',
            name='content_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='rule',
            name='content_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='rule',
            name='content_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='tariff',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tariff',
            name='name_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tariff',
            name='name_uz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='tariff',
            unique_together={('company', 'name'), ('company', 'name_en'), ('company', 'name_ru'), ('company', 'name_uz')},
        ),
    ]
