# Generated by Django 6.0.3 on 2026-03-21 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0014_alter_tariff_unique_together_message_text_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleslink',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='saleslink',
            name='name_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='saleslink',
            name='name_uz',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
